spring.application.name=user-service
server.port=8080


# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3307/home-energy-tracker
spring.datasource.username=root
spring.datasource.password=password
#driver is a java library that allows us to talk to db, different db have different drivers for mysql this is it
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# telling mysql to generate sql that is compatible with MYSQL (auto-detected in spring boot 4)
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# cuz we are using flyway we dont want the hibernate/jpa to auto create tables for us
spring.jpa.hibernate.ddl-auto=none


springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.client-id=swagger-ui

